export const ROUTE_CONSTANTS = {
    BASE: '/',
    LOGIN: '/login',
    DASHBOARD: '/dashboard',
    PAGE_NOT_FOUND: '/page-not-found',
    USERS: '/users',
    ROLES: '/roles',
    WORKS: '/works',
    DEPARTMENTS: '/departments',
    USER_PROFILE: '/profile',
    ROASTER: '/roaster',
    OBSERVATIONS: '/observations',
    INVENTORY: '/inventory',
    CONFIGURATIONS: '/configurations',
    CLUSTER: '/cluster',
    CLUSTER_DETAILS: '/cluster/:id',
    REQUESTS: "/requests",
    SEARCH: "/search",
    SERVER_MONITORING: "/server-monitoring",
    ATTENDANCE: "/attendance",
}