export const PRIVILEGES = {
    DASHBOARD_VIEW: "View Dashboard",
    USER_CREATE: "Create User",
    USER_VIEW: "View User",
    USER_UPDATE: "Update User",
    USER_DELETE: "Delete User",
    ROLE_CREATE: "Create Role",
    ROLE_VIEW: "View Role",
    ROLE_UPDATE: "Update Role",
    ROLE_DELETE: "Delete Role",
    WORK_CREATE: "Create Work",
    WORK_VIEW: "View All Work",
    WORK_VIEW_ASSIGNED: "View Assigned Work",
    WORK_UPDATE: "Update Work",
    WORK_DELETE: "Delete Work",
    DEPARTMENT_CREATE: "Create Department",
    DEPARTMENT_VIEW: "View Department",
    DEPARTMENT_UPDATE: "Update Department",
    DEPARTMENT_DELETE: "Delete Department",
    ROASTER_CREATE: "Create Roaster",
    ROASTER_VIEW: "View Roaster",
    ROASTER_UPDATE: "Update Roaster",
    ROASTER_DELETE: "Delete Roaster",
    ROASTER_APPROVE: "Approve Roaster",
    OBSERVATION_CREATE: "Create Observation",
    OBSERVATION_VIEW: "View Observations",
    OBSERVATION_UPDATE: "Update Observation",
    OBSERVATION_DELETE: "Delete Observation",
    INVENTORY_CREATE: "Create Inventory",
    INVENTORY_VIEW: "View Inventory",
    INVENTORY_UPDATE: "Update Inventory",
    INVENTORY_DELETE: "Delete Inventory",
    CONFIGURATION_CREATE: "Create Configuration",
    CONFIGURATION_VIEW: "View Configurations",
    CONFIGURATION_UPDATE: "Update Configurations",
    CONFIGURATION_DELETE: "Delete Configurations",
    SERVER_DETAILS_VIEW: "View Server Details",
    SERVER_DETAILS_CREATE: "Create Server Details",
    SERVER_DETAILS_UPDATE: "Update Server Details",
    SERVER_DETAILS_DELETE: "Delete Server Details",
    CREATE_SERVER_DETAILS: "Create Server Details",
    UPDATE_SERVER_DETAILS: "Update Server Details",
    DELETE_SERVER_DETAILS: "Delete Server Details",
    VIEW_SERVER_DETAILS: "View Server Details",
    CLUSTER_VIEW:"View Cluster",
    CLUSTER_CREATE:"Create Cluster",
    CLUSTER_UPDATE:"Update Cluster",
    CLUSTER_DELETE:"Delete Cluster",
    REQUEST_VIEW:"Request View",
    REQUEST_CREATE:"Request Create",
    REQUEST_UPDATE:"Request Update",
    REQUEST_DELETE:"Request Delete"
}