export const PRIVILEGES = {
    DASHBOARD_VIEW: "View Dashboard",
    USER_CREATE: "Create User",
    USER_VIEW_ALL: "View All Users",
    USER_VIEW_DEPT: "View Department Users",
    USER_UPDATE: "Update User",
    USER_DELETE: "Delete User",
    ROLE_CREATE: "Create Role",
    ROLE_VIEW: "View Role",
    ROLE_UPDATE: "Update Role",
    ROLE_DELETE: "Delete Role",
    WORK_CREATE: "Create Work",
    WORK_VIEW: "View All Work",
    WORK_VIEW_ASSIGNED: "View Assigned Work",
    WORK_UPDATE: "Update Work",
    WORK_DELETE: "Delete Work",
    DEPARTMENT_CREATE: "Create Department",
    DEPARTMENT_VIEW: "View Department",
    DEPARTMENT_UPDATE: "Update Department",
    DEPARTMENT_DELETE: "Delete Department",
    ROASTER_CREATE: "Create Roaster",
    ROASTER_VIEW: "View Roaster",
    ROASTER_UPDATE: "Update Roaster",
    ROASTER_DELETE: "Delete Roaster",
    ROASTER_APPROVE: "Approve Roaster",
    OBSERVATION_CREATE: "Create Observation",
    OBSERVATION_VIEW: "View Observations",
    OBSERVATION_UPDATE: "Update Observation",
    OBSERVATION_DELETE: "Delete Observation",
    INVENTORY_CREATE: "Create Inventory",
    INVENTORY_VIEW_ALL: "View All Inventory",
    INVENTORY_VIEW_DEPT: "View Department Inventory",
    INVENTORY_UPDATE: "Update Inventory",
    INVENTORY_DELETE: "Delete Inventory",
    CONFIGURATION_CREATE: "Create Configuration",
    CONFIGURATION_VIEW: "View Configurations",
    CONFIGURATION_UPDATE: "Update Configurations",
    CONFIGURATION_DELETE: "Delete Configurations",
    SERVER_DETAILS_VIEW: "View Server Details",
    SERVER_DETAILS_CREATE: "Create Server Details",
    SERVER_DETAILS_UPDATE: "Update Server Details",
    SERVER_DETAILS_DELETE: "Delete Server Details",
    CREATE_SERVER_DETAILS: "Create Server Details",
    UPDATE_SERVER_DETAILS: "Update Server Details",
    DELETE_SERVER_DETAILS: "Delete Server Details",
    VIEW_SERVER_DETAILS: "View Server Details",
    CLUSTER_VIEW:"View Cluster",
    CLUSTER_CREATE:"Create Cluster",
    CLUSTER_UPDATE:"Update Cluster",
    CLUSTER_DELETE:"Delete Cluster",
    REQUEST_VIEW: "View Request",
    REQUEST_CREATE: "Create Request",
    REQUEST_UPDATE: "Update Request",
    REQUEST_DELETE: "Delete Request",
    SEARCH_VIEW: "View Search",
    SEARCH_CREATE: "Create Search",
    SEARCH_UPDATE: "Update Search",
    SEARCH_DELETE: "Delete Search",
    SERVER_MONITORING_VIEW: "View Server Monitoring",
    SERVER_MONITORING_CREATE: "Create Server Monitoring",
    SERVER_MONITORING_UPDATE: "Update Server Monitoring",
    SERVER_MONITORING_DELETE: "Delete Server Monitoring",
    ATTENDANCE_CREATE: "Create Attendance",
    ATTENDANCE_UPDATE: "Update Attendance",
    ATTENDANCE_DELETE: "Delete Attendance",
    VIEW_DEPARTMENTAL_ATTENDACE: "View Departmental Attendance",
    VIEW_SELF_ATTENDANCE: "View Self Attendance",
    VIEW_ALL_ATTENDACE: "View All Attendance",
}