export default {
  dataCentreManagement: "Datacentre Management System",
  dcm: "DCM",
  dashboard: "Dashboard",
  logout: "Logout",
  login: "Login",
  username: "Username",
  password: "Password",
  loginError: "Invalid username or password",
  welcome: "Welcome",
  users: "Users",
  comingSoon: "Coming Soon",
  roles: "Roles",
  works: "Works",
  departments: "Departments",
  roaster: "Roaster",
  observations: "Observations",
  inventory: "Inventory",
  configurations: "Configurations",
  serverDetails: "Server Details",
  clusters: "Clusters",
  requests: "Requests",
  search: "Search",
  serverMonitoring: "Server Monitoring",
  attendance: "Attendance",
  auditLogs: "Audit Logs",
  documentations: "Documentations",
  bmsChecklist: "BMS Checklist",
  visitorLogs: "Visitor Logs",
  dailyActivities: "Daily Activities",
  morningChecklist: "Morning Checklist",
};
